import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<aside className="flex flex-col items-center">
					<Link href="/">Home</Link>
					<Link href="/login">Log In</Link>
					<Link href="">Log Out</Link>
				</aside>
				<main className="min-h-screen p-2 flex flex-col items-center">
					{children}
				</main>
			</body>
		</html>
	);
}
